version: "3"
services:
  server:
    image: node:latest
    command: bash -c 'while true; do sleep 60; done'
    environment:
      - NODE_ENV=development
    env_file:
      - .env.docker
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - ./data/server/share:/share

  mongo:
    env_file:
      - .env.docker
    volumes:
      - ./data/mongo/share:/share
